gitlab:
  user: root
  rootPassword: openshift
  host: 
  email:
    address: "gitlab@rhdemo.com"
    displayName: "Gitlab"

parasol:
  group: parasol
  store:
    templates: []
    argocd:
      name: parasol-store-build
      namespace:
    image:
      name: parasol-store
    gitlab:
      group: parasol
      repo: parasol-store
    manifests:
      files:
        dev: app/values/values-dev.yaml
        staging: app/values/values-staging.yaml
        prod: app/values/values-prod.yaml
      gitlab:
        group: parasol
        repo: parasol-store-manifests
        branch:
          dev: main
          staging: staging
          prod: prod

registry:
  host:
  organization: parasol
  username:
  password:

cluster:
  subdomain: