keycloak:
  name: keycloak

realm:
  name: backstage

hook:
  serviceAccount:
    create: true
    name: ""
  image:
    repository: quay.io/cloud-architecture-workshop/wait-for-statefulset-job
    pullPolicy: IfNotPresent
    tag: "1c68180"
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  maxTimeToWait: 120000

argocd:
  enabled: true
  syncwave: "-1"

backstage:
  redirectUri:
  webOrigin:

identityProvider:
  gitlab:
    name: gitlab
    authorizationUrl: 
    tokenUrl: 
    clientId:
    clientSecret:
