kind: Secret
apiVersion: v1
metadata:
  name: kubernetes-sa-token
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
stringData:
  KUBERNETES_SA_TOKEN: {{ .Values.backstage.kubernetes.sa_token }}
type: Opaque
