kind: Secret
apiVersion: v1
metadata:
  name: oauth-client
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
stringData:
  OAUTH_CLIENT_ID: {{ .Values.backstage.oauth.clientId }}
  OAUTH_CLIENT_SECRET: {{ .Values.backstage.oauth.clientSecret }}
type: Opaque
